#!/usr/bin/python3
import subprocess
import sys


res = subprocess.run(['ghc', '-e', 'Test.main', 'Test.hs'], stdout=subprocess.PIPE, stderr=subprocess.PIPE)
if not res.stderr:
	sys.stdout.buffer.write(res.stdout)
	# subprocess.run(['./test'])
else:
	sys.stderr.buffer.write(res.stderr)
